# Generated by Django 3.2.8 on 2021-10-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='defualt.jpg', upload_to='profile_pics'),
        ),
    ]
