# Generated by Django 3.2.8 on 2021-10-13 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_testpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auth',
            new_name='author',
        ),
        migrations.DeleteModel(
            name='Testpost',
        ),
    ]
